### ISSUE TITLE
How is this different from the existing msgpack node?

### ISSUE THREAD

**Issue by dceejay** [xTheRamon/node-red-contrib-msgpack#1]
Hi, how is this different to the existing node-red-node-msgpack node ? Do we need both? Please make it clear in the readme. If there is something missing from the existing one then maybe a pull request is a better option ?

**Comment by xTheRamon** [comment]
Dear dave,

The existing `node-red-node-msgpack` uses an old version of msgpack, namely `msgpack-js`. I basically updated `node-red-node-msgpack` and implemented the newer `msgpack` library.

The old `msgpack-js` gave me an error complaining about `readUInt64BE` not being part of the `Buffer` class. The newer library fixes this issue. I figured many people are using the older `node-red-node-msgpack` (with the extended bops library that solves the `readUInt64BE` issue), that's why I decided to create a newer `node-red-contrib-msgpack` for people starting new, just like myself.

I'll update the readme, good suggestion. Thank you.

**Comment by dceejay** [comment]
Does the underlying library have precompiled support for windows ? They often don't have GCC installed , so not so easy for beginners there.
If it does then I would have preferred it to be a PR against the existing node, (and why not raise an issue against it first). 

Also not impressed you copied the code with no attribution to the existing, and changed the license.

**Comment by dceejay** [comment]
Hi - I have now updated the node-red-node version to use msgpack-lite library which is pure js and claims to be even faster... and supports 64bit ints and the newer msgpack spec - so hopefully that covers the bases.
https://www.npmjs.com/package/node-red-node-msgpack

**Comment by xTheRamon** [comment]
Hi @dceejay 

I have not had any time yet to create a pull request on your `node-red-node-msgpack`.
I have tested the recent changes you've made, and can confirm the `msgpack-lite` library is working!

I will remove this repository now, thank you for your effort.
